version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "v2"
    schedule:
      interval: "daily"

  - package-ecosystem: gomod
    directory: "/"
    target-branch: "v2"
    schedule:
      interval: daily
