// Code generated by protoc-gen-go. DO NOT EDIT.
// source: key.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Key struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	IntID                int64    `protobuf:"varint,3,opt,name=IntID,proto3" json:"IntID,omitempty"`
	NameID               string   `protobuf:"bytes,4,opt,name=NameID,proto3" json:"NameID,omitempty"`
	Parent               *Key     `protobuf:"bytes,5,opt,name=Parent,proto3" json:"Parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_2accf5df6005b7d4, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Key) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Key) GetIntID() int64 {
	if m != nil {
		return m.IntID
	}
	return 0
}

func (m *Key) GetNameID() string {
	if m != nil {
		return m.NameID
	}
	return ""
}

func (m *Key) GetParent() *Key {
	if m != nil {
		return m.Parent
	}
	return nil
}

func init() {
	proto.RegisterType((*Key)(nil), "proto.Key")
}

func init() { proto.RegisterFile("key.proto", fileDescriptor_2accf5df6005b7d4) }

var fileDescriptor_2accf5df6005b7d4 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4e, 0xad, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x9d, 0x8c, 0x5c, 0xcc, 0xde, 0xa9,
	0x95, 0x42, 0x32, 0x5c, 0x9c, 0x7e, 0x89, 0xb9, 0xa9, 0xc5, 0x05, 0x89, 0xc9, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x21, 0x21, 0x2e, 0x16, 0xef, 0xcc, 0xbc, 0x14, 0x09,
	0x26, 0xb0, 0x04, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0xea, 0x99, 0x57, 0xe2, 0xe9, 0x22, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0xe1, 0x08, 0x89, 0x71, 0xb1, 0x81, 0xb4, 0x79, 0xba, 0x48, 0xb0,
	0x80, 0xd5, 0x42, 0x79, 0x42, 0x4a, 0x5c, 0x6c, 0x01, 0x89, 0x45, 0xa9, 0x79, 0x25, 0x12, 0xac,
	0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x5c, 0x10, 0x67, 0xe8, 0x79, 0xa7, 0x56, 0x06, 0x41, 0x65, 0x92,
	0xd8, 0xc0, 0x42, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xf2, 0x94, 0x4f, 0xa6, 0x00,
	0x00, 0x00,
}
